
package net.webservicex;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "StatisticsSoap", targetNamespace = "http://www.webserviceX.NET")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StatisticsSoap {


    /**
     * Statistical (Sum,Average,Standard Deviation,skewness and Kurtosis)
     * 
     * @param kurtosis
     * @param sums
     * @param standardDeviation
     * @param skewness
     * @param average
     * @param x
     */
    @WebMethod(operationName = "GetStatistics", action = "http://www.webserviceX.NET/GetStatistics")
    @RequestWrapper(localName = "GetStatistics", targetNamespace = "http://www.webserviceX.NET", className = "net.webservicex.GetStatistics")
    @ResponseWrapper(localName = "GetStatisticsResponse", targetNamespace = "http://www.webserviceX.NET", className = "net.webservicex.GetStatisticsResponse")
    public void getStatistics(
        @WebParam(name = "X", targetNamespace = "http://www.webserviceX.NET")
        ArrayOfDouble x,
        @WebParam(name = "Sums", targetNamespace = "http://www.webserviceX.NET", mode = WebParam.Mode.OUT)
        Holder<Double> sums,
        @WebParam(name = "Average", targetNamespace = "http://www.webserviceX.NET", mode = WebParam.Mode.OUT)
        Holder<Double> average,
        @WebParam(name = "StandardDeviation", targetNamespace = "http://www.webserviceX.NET", mode = WebParam.Mode.OUT)
        Holder<Double> standardDeviation,
        @WebParam(name = "skewness", targetNamespace = "http://www.webserviceX.NET", mode = WebParam.Mode.OUT)
        Holder<Double> skewness,
        @WebParam(name = "Kurtosis", targetNamespace = "http://www.webserviceX.NET", mode = WebParam.Mode.OUT)
        Holder<Double> kurtosis);

}
